apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.helm_service_account_0a1567a7bcad51b798e614fe57e3f0e3.name  }}
  labels:
  {{- range $key, $value := .Values.helm_service_account_0a1567a7bcad51b798e614fe57e3f0e3.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.helm_service_account_0a1567a7bcad51b798e614fe57e3f0e3.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
automountServiceAccountToken: {{ .Values.helm_service_account_0a1567a7bcad51b798e614fe57e3f0e3.automount }}
